### ISSUE TITLE
Impossible to export vars in rabbitmq-env.conf

### ISSUE THREAD

**Issue by ajsalminen** [michaelrigart/ansible-role-rabbitmq#2]
[Some configurations](http://serverfault.com/questions/235669/how-do-i-make-rabbitmq-listen-only-to-localhost) require you to export the vars in rabbitmq-env.conf but with the current key-value pair method it's not possible.

How do you think it should be solved? I thought of just going with same way the /etc/default/rabbitmq-server is done where you just specify full lines, what do you think of that?

I'm mostly looking to get rabbitmq to listen only on loopback by default, would you accept a patch for adding the required lines to the template and a configuration option? I imagine there may be some other cases where an export or something else is needed so it might be a good idea to make the config more flexible as well though.

**Comment by michaelrigart** [comment]
Hey @ajsalminen,

I have encountered this issue before with other roles as well. I find key-value pairing easy to keep a nice  overview of all variables and values. The downside is, that it numbs down the possibilities for structuring other data types. Other config files can for instance also require a specific order of variables. 

In those cases (perhaps also this case for adding export variables), it might perhaps be easier to use an array of strings:
- 'export RABBITMQ_NODENAME=rabbit@localhost'
- 'export RABBITMQ_NODE_IP_ADDRESS=127.0.0.1'
- 'export ERL_EPMD_ADDRESS=127.0.0.1'
- 'NODENAME=hare'
- 'CONFIG_FILE=/usr/local/etc/rabbitmq/rabbitmq'

Then we can simply loop the array elements inside the template.

**Comment by ajsalminen** [comment]
Hi,

Thanks for the quick response! I agree that this would probably be a good solution here. The pull request in #3 should do what you suggested.
